### ISSUE TITLE
Предложение по поводу репозитории.

### ISSUE THREAD

**Issue by iGilga** [SuperBugCompany/politrange#1]
Сливать исходный код в единственном репозитории и тем более в ветке мастера это ущербно.

Предлагаю, создать несколько репозитории, на которых будут вести разработку по компоненте.
Например.
- SuperBugCompany / politrange.webapi
- SuperBugCompany / politrange.android
- SuperBugCompany / politrange.desktop
- SuperBugCompany / politrange.crawler
- SuperBugCompany / politrange.web
- SuperBugCompany / politrange.sql

Как вы думаете?

**Comment by Kartavec** [comment]
А что делать, если разные компоненты будут переиспользовать один и тот же код?
Чем идея с разными репозиториями лучше, чем если каждый будет писать в своей папке, но в одном репозитории?

**Comment by iGilga** [comment]
Переиспользование кода выделять его в качестве библиотеки. 
Идея с разными репозиториями как разложить по палочкам.
Идея каждый в своей папке, может лучше заливать в своей ветке?
Ведь может только руководитель решает принимать код или нет в ветке мастера, верно?

**Comment by akhorevich** [comment]
А в чем ущербность то? Нас 6 человек, и кода у нас не сказать что очень много. А разводить бодягу на 6 папок - хз. Тем более что у нас большинство делают задачи по разным компонентам

**Comment by Kartavec** [comment]
Про переиспользование кода. Если его выделить в качестве библиотеки, то эта библиотека тоже должна быть в отдельном репозитории, получается?

Каждый работает в отдельной ветке над конкретной задачей. По готовности - самостоятельно сливает в master. Я буду делать Review того, что получается. Есть разные подходы к разработке.

Посмотрим, что получится. Возможно вы правы, и потребуется делать review кода каждой ветки перед слиянием её в master.

**Comment by Kartavec** [comment]
Можно в принципе делать каждому свой форк, а потом pull request-ы, но имхо это целесообразно для крупных open-source проектов.

**Comment by iGilga** [comment]
Доброе утро, да в отдельном репозитории. В репозитории указать версии релиза и создать ссылку на dll файл или исходный код. Отсюда скачать библиотеки.
Хорошо, мое предложение отвергнуты. Оставим как есть.

**Comment by iGilga** [comment]
оффтоп: по поводу веб-сервис есть прогресс?
